=== gkislin/FileSynchronizer/xml_storage/userSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="https://cargoonline.ru"
           attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="https://cargoonline.ru">

    <xs:element name="XMLUsers">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="XMLUser"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="XMLUser">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="username"/>
                <xs:element type="xs:string" name="firstname"/>
                <xs:element type="xs:string" name="lastname"/>
                <xs:element type="xs:date" name="birth"/>
                <xs:element type="addressType" name="address"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="code"/>
            <xs:attribute type="xs:int" name="age"/>
            <xs:attribute type="flagType" name="flag"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element type="xs:string" name="country"/>
            <xs:element type="xs:string" name="city"/>
            <xs:element type="xs:string" name="street"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== gkislin/FileSynchronizer/xml_storage/user4.xml
<XMLUser xmlns="https://cargoonline.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://cargoonline.ru userSchema.xsd"
         code="U4" age="44" flag="superuser">

    <username>User4</username>
    <firstname>FirstName4</firstname>
    <lastname>LastName4</lastname>
    <birth>2002-11-24</birth>
    <address>
        <country>Russia</country>
        <city>St. Petersburg</city>
        <street>Mira</street>
    </address>
</XMLUser>

=== gkislin/FileSynchronizer/xml_storage/user1.xml
<XMLUser xmlns="https://cargoonline.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://cargoonline.ru userSchema.xsd"
         code="U1" age="11" flag="active">

    <username>User1</username>
    <firstname>Имя1</firstname>
    <lastname>Фамилия1</lastname>
    <birth>2002-09-24</birth>
    <address>
        <country>Россия</country>
        <city>St. Petersburg</city>
        <street>Mira</street>
    </address>
</XMLUser>
